export const ERROR_CODES = {
  INSUFFICIENT_COINS: 'INSUFFICIENT_COINS',
  ROOM_FULL: 'ROOM_FULL',
  SEAT_TAKEN: 'SEAT_TAKEN',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  ALREADY_FOLLOWING: 'ALREADY_FOLLOWING',
  LEVEL_MAX: 'LEVEL_MAX',
  FAMILY_FULL: 'FAMILY_FULL',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
