import { Router } from 'express';
import { authenticateAdmin } from '../../middleware/admin-auth.middleware';

import adminAuthRouter from './auth/admin-auth.routes';
import dashboardRouter from './dashboard/dashboard.routes';
import adminUsersRouter from './users/admin-users.routes';
import adminRoomsRouter from './rooms/admin-rooms.routes';
import adminGiftsRouter from './gifts/admin-gifts.routes';
import adminPaymentsRouter from './payments/admin-payments.routes';
import settingsRouter from './settings/settings.routes';
import auditRouter from './audit/audit.routes';
import adminModerationRouter from './moderation/admin-moderation.routes';
import adminHostAppsRouter from './host-applications/admin-host-apps.routes';
import analyticsRouter from './analytics/analytics.routes';
import adminAgenciesRouter from './agencies/admin-agencies.routes';
import commissionConfigRouter from './commission-config/commission-config.routes';
import adminLuckyGiftsRouter from './lucky-gifts/lucky-gifts.routes';
import { adminRouter as agencyInvitationsAdminRouter } from '../agency-invitations/agency-invitations.routes';
import adminGamesRouter from './games/admin-games.routes';
import adminRolesRouter from './roles/admin-roles.routes';
import adminEventsRouter from './events/admin-events.routes';
import adminBannersRouter from './banners/admin-banners.routes';
import adminAgencyLearnPromotionsRouter from './agency-learn-promotions/admin-agency-learn-promotions.routes';
import designatedBecomeAgencyAdminsRouter from './designated-become-agency-admins/designated-become-agency-admins.routes';
import adminThemesRouter from './themes/admin-themes.routes';
import adminRiskControlRouter from './risk-control/admin-risk-control.routes';
import adminMasterWalletRouter from './master-wallet/master-wallet.routes';
import adminTagsRouter from './tags/admin-tags.routes';
import adminSpecialIdsRouter from './special-ids/admin-special-ids.routes';
import adminSupportRouter from './support/admin-support.routes';
import adminStoreRouter from './store/admin-store.routes';
import adminFamiliesRouter from './families/admin-families.routes';
import adminLevelTasksRouter from './level-tasks/admin-level-tasks.routes';
import adminSellerCoinsRouter from './seller-coins/admin-seller-coins.routes';
import adminPayrollRouter from './payroll/admin-payroll.routes';
import hostChangeRequestsRouter from './host-change-requests/host-change-requests.routes';
import agentApplicationsRouter from './agent-applications/agent-applications.routes';
import adminNotificationsRouter from './notifications/admin-notifications.routes';
import adminTeamAnnouncementsRouter from './team-announcements/admin-team-announcements.routes';
import adminFaceVerificationRouter from './face-verification/admin-face-verification.routes';
import adminBdRouter from './bd/admin-bd.routes';
import adminCsRouter from './cs/admin-cs.routes';
import adminRegionsRouter from './regions/admin-regions.routes';
import adminTargetsRouter from './targets/admin-targets.routes';
import adminHostsRouter from './hosts/admin-hosts.routes';
import adminHierarchyRouter from './hierarchy/admin-hierarchy.routes';
import adminMaintenanceRouter from './maintenance/maintenance.routes';
import adminStateRankingRouter from './state-ranking/admin-state-ranking.routes';
import adminRankingRewardsRouter from './ranking-rewards/admin-ranking-rewards.routes';

const router = Router();

// Auth routes (login/refresh are public, rest need auth — handled internally)
router.use('/auth', adminAuthRouter);

// All routes below require admin authentication
router.use('/dashboard',         authenticateAdmin, dashboardRouter);
router.use('/users',             authenticateAdmin, adminUsersRouter);
router.use('/rooms',             authenticateAdmin, adminRoomsRouter);
router.use('/gifts',             authenticateAdmin, adminGiftsRouter);
router.use('/payments',          authenticateAdmin, adminPaymentsRouter);
router.use('/settings',          authenticateAdmin, settingsRouter);
router.use('/audit-log',         authenticateAdmin, auditRouter);
router.use('/moderation',        authenticateAdmin, adminModerationRouter);
router.use('/host-applications', authenticateAdmin, adminHostAppsRouter);
router.use('/analytics',         authenticateAdmin, analyticsRouter);
router.use('/agencies',          authenticateAdmin, adminAgenciesRouter);
router.use('/lucky-gifts',       authenticateAdmin, adminLuckyGiftsRouter);
router.use('/',                  authenticateAdmin, commissionConfigRouter);
router.use('/',                  authenticateAdmin, agencyInvitationsAdminRouter);
router.use('/games',             authenticateAdmin, adminGamesRouter);
router.use('/roles',             authenticateAdmin, adminRolesRouter);
router.use('/events',            authenticateAdmin, adminEventsRouter);
router.use('/banners',           authenticateAdmin, adminBannersRouter);
router.use('/agency-learn-promotions', authenticateAdmin, adminAgencyLearnPromotionsRouter);
router.use('/designated-become-agency-admins', authenticateAdmin, designatedBecomeAgencyAdminsRouter);
router.use('/themes',            authenticateAdmin, adminThemesRouter);
router.use('/risk-control',      authenticateAdmin, adminRiskControlRouter);
router.use('/master-wallet',     authenticateAdmin, adminMasterWalletRouter);
router.use('/tags',              authenticateAdmin, adminTagsRouter);
router.use('/special-ids',       authenticateAdmin, adminSpecialIdsRouter);
router.use('/support',           authenticateAdmin, adminSupportRouter);
router.use('/store',             authenticateAdmin, adminStoreRouter);
router.use('/families',          authenticateAdmin, adminFamiliesRouter);
router.use('/level-tasks',       authenticateAdmin, adminLevelTasksRouter);
router.use('/seller-coins',      authenticateAdmin, adminSellerCoinsRouter);
router.use('/payroll',               authenticateAdmin, adminPayrollRouter);
router.use('/host-change-requests',  authenticateAdmin, hostChangeRequestsRouter);
router.use('/agent-applications',    authenticateAdmin, agentApplicationsRouter);
router.use('/notifications',         authenticateAdmin, adminNotificationsRouter);
router.use('/team-announcements',     authenticateAdmin, adminTeamAnnouncementsRouter);
router.use('/face-verifications',     authenticateAdmin, adminFaceVerificationRouter);
router.use('/bd',                     authenticateAdmin, adminBdRouter);
router.use('/cs',                     authenticateAdmin, adminCsRouter);
router.use('/regions',               authenticateAdmin, adminRegionsRouter);
router.use('/targets',               authenticateAdmin, adminTargetsRouter);
router.use('/hosts',                 authenticateAdmin, adminHostsRouter);
router.use('/management',             authenticateAdmin, adminHierarchyRouter);
router.use('/maintenance',            authenticateAdmin, adminMaintenanceRouter);
router.use('/state-ranking',          authenticateAdmin, adminStateRankingRouter);
router.use('/ranking-rewards',        authenticateAdmin, adminRankingRewardsRouter);

export default router;
